WITH T AS (
    SELECT CRCC.CAR_ID, CRCC.CAR_TYPE , FLOOR(CRCC.DAILY_FEE * 30 * (1 - CRCDP.DISCOUNT_RATE / 100)) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR CRCC
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCDP ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE 
        AND CRCDP.DURATION_TYPE = '30일 이상'
    WHERE CRCC.CAR_TYPE IN ('세단', 'SUV')
        AND CRCC.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
        AND END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
    )
        AND FLOOR(CRCC.DAILY_FEE * 30 * (1 - CRCDP.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 2000000
    )

SELECT *
FROM T
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID