WITH T AS (
    SELECT COUNT(UGB.WRITER_ID),UGU.USER_ID, UGU.NICKNAME, UGU.CITY ,UGU.STREET_ADDRESS1, UGU.STREET_ADDRESS2, SUBSTR(UGU.TLNO,1,3) || '-' || SUBSTR(UGU.TLNO,4,4) || '-' || SUBSTR(UGU.TLNO,8,4) AS TLNO
    FROM USED_GOODS_BOARD UGB
    JOIN USED_GOODS_USER UGU ON UGB.WRITER_ID = UGU.USER_ID
    GROUP BY UGU.USER_ID,UGU.NICKNAME,UGU.CITY,UGU.STREET_ADDRESS1,UGU.STREET_ADDRESS2,UGU.TLNO
    HAVING COUNT(UGB.WRITER_ID) >= 3
) SELECT T.USER_ID AS USER_ID, T.NICKNAME AS NICKNAME, T.CITY || ' ' || T.STREET_ADDRESS1 || ' ' || T.STREET_ADDRESS2 AS 전체주소, T.TLNO AS 전화번호
FROM T
ORDER BY T.USER_ID DESC
    